
ERROR_CODE_LIST={}

# Successful - 2xx
# HTTP_200_OK

# HTTP_201_CREATED

# HTTP_202_ACCEPTED
ERROR_CODE_LIST['ACCEPTED']="202"
ERROR_CODE_LIST['SUCCESS']="202"

# Client Error - 4xx
# HTTP_400_BAD_REQUEST


ERROR_CODE_LIST['RECORD_NOT_FOUND']="400"
ERROR_CODE_LIST['RECORD_NOT_INSERTED']="400-1"
ERROR_CODE_LIST['MANDATORY_PARAMETER_NOT_SPECIFIED']="404-6"
ERROR_CODE_LIST['TOKEN_ERROR']="401-3"
ERROR_CODE_LIST['USER_NOT_AUTHORIZED']="400-113"
ERROR_CODE_LIST['RECORD_NOT_DELETED']="400-2"
ERROR_CODE_LIST['MESSAGEBOARD_NOT_CREATED']="400-3"
ERROR_CODE_LIST['CONTENT_NOT_ACCESSIBLE'] = "404-3"
ERROR_CODE_LIST['QUESTION_NUMBER_ALREADY_EXISTS']="400-12"